### ISSUE TITLE
Crashing by items from Spiral Knights

### ISSUE THREAD

**Issue by escalante1337** [DoctorMcKay/node-steam-tradeoffer-manager#10]
So, i have a lottery site, which used node-steam-tradeoffer-manager and i found problem, when someone send me offer with items from game Spiral Knights like this my bot crash by library error: 
![Offer](http://f1.s.qip.ru/12K4cQXfs.png)
With this error:
```
/var/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:124
		item.assetid = item.id = (item.assetid || item.id).toString();
		                                                  ^
TypeError: Cannot read property 'toString' of undefined
    at /var/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:124:53
    at Array.map (native)
    at processItems (/var/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:123:15)
    at createOfferFromData (/var/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:106:25)
    at /var/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:92:12
    at Array.map (native)
    at /var/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:91:63
    at TradeOfferManager.<anonymous> (/var/bot/node_modules/steam-tradeoffer-manager/lib/assets.js:128:3)
    at /var/bot/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:52:16
    at /var/bot/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:363:13
```
So, how i fix this?
File node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js
in function checkNeededDescriptions
instead of
```
if(!manager._hasDescription(item))
```
i write
```
if(!manager._hasDescription(item) || (typeof item.id == 'undefined' && typeof item.assetid == 'undefined'))
```
I think, it must be fixed. Sorry for my bad english, i just tried to help

**Comment by DoctorMcKay** [comment]
[Fixed in 1.8.3](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases/tag/v1.8.3). Thanks for the report.
