### ISSUE TITLE
input.match is not a function

### ISSUE THREAD

**Issue by simonsimon006** [DoctorMcKay/node-steam-tradeoffer-manager#117]
When i create a new tradeOffer with TradeOfferManager
`offers.createOffer(config.steamId)` I get an exception:
`/usr/src/app/node_modules/steamid/index.js:72
	if((matches = input.match(/^STEAM_([0-5]):([0-1]):([0-9]+)$/))) {
	                    ^

TypeError: input.match is not a function
    at new SteamID (/usr/src/app/node_modules/steamid/index.js:72:22)
    at new TradeOffer (/usr/src/app/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:180:18)
    at TradeOfferManager.createOffer (/usr/src/app/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:10:14)
    at Object.MyObject.MyFunction (/usr/src/app/modules/myfile.js:104:27)
    at /usr/src/app/index.js:216:24
    at SteamCommunity.<anonymous> (/usr/src/app/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:698:4)
    at Request._callback (/usr/src/app/node_modules/steamcommunity/components/http.js:62:14)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
       tags: [Obj`

**Comment by DoctorMcKay** [comment]
What version are you running? What type is `config.steamId`?

**Comment by simonsimon006** [comment]
I figured it out, I used the 64bit steamID as number, not as string. Sorry for causing you trouble.
