### ISSUE TITLE
Sentofferchanged sometimes can`t detect state change.

### ISSUE THREAD

**Issue by MaTyyyJ** [DoctorMcKay/node-steam-tradeoffer-manager#12]
Hi. I have a problem. Sometimes manager cant see a state's change from Active to Accepted, I don`t know where is the reason, but I saw, that manager... That manager is stopping to see this offer. I think, problem is there - offer goes to historical state, but BOT is checking a state only for Active

**Comment by DoctorMcKay** [comment]
How often does this happen?

**Comment by MaTyyyJ** [comment]
Steam sucks everyday... Becouse of it, this problem happens... Hmm... 20 times in one day?

**Comment by MaTyyyJ** [comment]
It happens when there is an error: HTTP error:504, 502 etc

**Comment by MaTyyyJ** [comment]
` Error: HTTP error 504
    at SteamCommunity._checkHttpError (~/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/index.js:320:15)
    at Request._callback (~/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/components/users.js:260:12)
    at Request.self.callback (~/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (~/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/node_modules/request/request.js:1063:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (~/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)`

**Comment by DoctorMcKay** [comment]
Is that crashing you, or are you just printing the Error's stack trace?

Either way, that stack is coming from a call to `TradeOfferManager#loadInventory` or `TradeOffer#loadPartnerInventory` somwhere. My guess is that the event is being emitted, you're loading the partner's inventory, and it's failing so you give up on the offer.

**Comment by MaTyyyJ** [comment]
My bad, but in console I recive error from acceptance an offer:  Couldn't get received items: Error: HTTP error 504 and past this errors, offer is not checking. Can I make, that bot check the offer until it receives skins?

**Comment by DoctorMcKay** [comment]
That's happening because of an error on Steam's end when you're calling `getReceivedItems`. There's nothing you can do except retry when you get such an error.
