### ISSUE TITLE
Error while sending or confirmating offers.

### ISSUE THREAD

**Issue by SzymonLisowiec** [DoctorMcKay/node-steam-tradeoffer-manager#140]
Hello,
I have error while sending or confirming offers, logs:
```
Received steamid in 64-bit (XXXXXXXXXXXXXXXXX)
node-steam-user ready
node-steamcommunity ready
node-steam-tradeoffer-manager ready
Steambot is ready!
Connected to MySQL
Offer#1229249415 changed state on Canceled [orderid:undefined]
Offer#1229255042 changed state on Canceled [orderid:undefined]
Offer#1229252357 changed state on Canceled [orderid:undefined]
Offer#1229252381 changed state on Canceled [orderid:undefined]
Offer#1229255037 changed state on Canceled [orderid:undefined]
Offer#1229253646 changed state on Canceled [orderid:undefined]
Offer#1229255029 changed state on Canceled [orderid:undefined]
Error when confrim STEP2: Error: Could not act on confirmation
Error when confrim STEP2: Error: Could not act on confirmation
Error when confrim STEP2: Error: Could not act on confirmation
Offer#1229314425 changed state on Sent [orderid:393796]
Error when confrim STEP2: Error: Could not act on confirmation
Error when confrim STEP2: Error: Could not act on confirmation
Offer#1229314429 changed state on Sent [orderid:393272]
Error when confrim STEP2: Error: Could not act on confirmation
Offer#1229314436 changed state on Sent [orderid:393784]
Offer#1229314422 changed state on Canceled [orderid:393778]
Offer#1229314425 changed state on Accepted [orderid:393796]
_http_outgoing.js:355
      throw new TypeError('The header content contains invalid characters');
      ^
TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:355:13)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (/root/node_modules/request/request.js:746:30)
    at Request.write (/root/node_modules/request/request.js:1345:10)
    at end (/root/node_modules/request/request.js:560:16)
    at Immediate._onImmediate (/root/node_modules/request/request.js:588:7)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
I have many bots running on the same script and only two of them have this error.

**Comment by DoctorMcKay** [comment]
I can't reproduce this. Make sure everything is up to date.

**Comment by SzymonLisowiec** [comment]
Two days ago the problem has been solved. It helped to update all libraries steam.
I forgoten to close issue, sorry.
