### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Kasp42** [DoctorMcKay/node-steam-tradeoffer-manager#154]
```
/root/bot/node_modules/steam-tradeoffer-manager/lib/index.js:8
const SteamID = TradeOfferManager.SteamID = require('steamid');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/bot/bot1.js:10:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```
NodeJs: 0.10.42
npm: 1.3.6
OS: CentOS 6.8

**Comment by scholtzm** [comment]
You'll need node v4 or higher.
