### ISSUE TITLE
Random crashing while getting escrow days

### ISSUE THREAD

**Issue by tolunlade** [DoctorMcKay/node-steam-tradeoffer-manager#162]
```
Got API key: <don't put api keys on github please>
New offer #1413634272 from [U:1:218971509]
/home/teslim/steam-bot/steam_bot.js:89
                                        if (them.escrowDays <= 0) {
                                                ^

TypeError: Cannot read property 'escrowDays' of undefined
    at /home/teslim/steam-bot/steam_bot.js:89:14
    at Object.exports.makeAnError (/home/teslim/steam-bot/node_modules/steam-tradeoffer-manager/lib/helpers.js:33:4)
    at manager._community.httpRequestGet (/home/teslim/steam-bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:752:12)
    at SteamCommunity._checkCommunityError (/home/teslim/steam-bot/node_modules/steamcommunity/components/http.js:123:3)
    at Request._callback (/home/teslim/steam-bot/node_modules/steamcommunity/components/http.js:51:88)
    at Request.self.callback (/home/teslim/steam-bot/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/teslim/steam-bot/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
Prices updated
Got API key: <don't put api keys on github please>
New offer #1414248920 from [U:1:216352834]
```

**Comment by DoctorMcKay** [comment]
Sounds to me like you aren't checking for errors.
