### ISSUE TITLE
TypeError: offer.getEscrowDuration is not a function

### ISSUE THREAD

**Issue by denr999** [DoctorMcKay/node-steam-tradeoffer-manager#164]
Is just my code outdated? I get this error 

SERVER] The Bot has logged in!
[DEBUG] Processing offer #1428519712 from xxx  (ID:xxx).
C:\xxx\BOT\bot.js:225
                offer.getEscrowDuration(function(err, daysTheirEscrow, daysMyEscrow)
                      ^

TypeError: offer.getEscrowDuration is not a function
    at C:\xxx\BOT\bot.js:225:9
    at Request._callback (C:\xxx\BOT\bot.js:136:4)
    at Request.self.callback (C:\xxx\BOT\node_modules\request\request.js:197:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\xxx\BOT\node_modules\request\request.js:1050:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\xxx\BOT\node_modules\request\request.js:996:12)
    at emitNone (events.js:72:20)

can someone help? if you want me to post the code let me know

**Comment by DoctorMcKay** [comment]
#156
