### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Syndromxx** [DoctorMcKay/node-steam-tradeoffer-manager#218]
im getting this error when im starting my app can anyone help me?
cookies.forEach(function(cookie) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at SteamCommunity.setCookies (/var/www/html/BOT/node_modules/steamcommunity/index.js:214:9)
    at TradeOfferManager.options._steam.on._steam.on.TradeOfferManager.setCookies.checkDone [as setCookies] (/var/www/html/BOT/node_modules/steam-tradeoffer-manager/lib/index.js:78:18)
    at /var/www/html/BOT/bot.js:84:25
    at /var/www/html/BOT/node_modules/steamcommunity/index.js:191:4
    at SteamCommunity._checkHttpError (/var/www/html/BOT/node_modules/steamcommunity/components/http.js:98:3)
    at Request._callback (/var/www/html/BOT/node_modules/steamcommunity/components/http.js:50:61)
    at Request.self.callback (/var/www/html/BOT/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/www/html/BOT/node_modules/request/request.js:1171:10)

**Comment by scholtzm** [comment]
The error message explains it all pretty well - you are calling [`setCookies`](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#setcookiescookies-familyviewpin-callback) with `undefined`.

**Comment by Syndromxx** [comment]
sorry i forgot a part of the error 

/var/www/html/BOT/node_modules/steamcommunity/index.js:214
        cookies.forEach(function(cookie) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at SteamCommunity.setCookies (/var/www/html/BOT/node_modules/steamcommunity/index.js:214:9)
    at TradeOfferManager.options._steam.on._steam.on.TradeOfferManager.setCookies.checkDone [as setCookies] (/var/www/html/BOT/node_modules/steam-tradeoffer-manager/lib/index.js:78:18)
    at /var/www/html/BOT/bot.js:84:25
    at /var/www/html/BOT/node_modules/steamcommunity/index.js:191:4
    at SteamCommunity._checkHttpError (/var/www/html/BOT/node_modules/steamcommunity/components/http.js:98:3)
    at Request._callback (/var/www/html/BOT/node_modules/steamcommunity/components/http.js:50:61)
    at Request.self.callback (/var/www/html/BOT/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/www/html/BOT/node_modules/request/request.js:1171:10)

**Comment by DoctorMcKay** [comment]
The error message explains it all pretty well - you are calling [`setCookies`](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#setcookiescookies-familyviewpin-callback) with `undefined`.
