### ISSUE TITLE
 callback(null, 'sent'); TypeError: callback is not a function 

### ISSUE THREAD

**Issue by thehelloand** [DoctorMcKay/node-steam-tradeoffer-manager#240]
Console throws this error when trying to create a trade offer: C:\Users\Logan\Desktop\steamkeybot\node_modules\trademanager1\lib\classes\TradeOffer.js:405
                        callback(null, 'sent');
                        ^

TypeError: callback is not a function
    at SteamCommunity.manager._community.httpRequestPost (C:\Users\Logan\Desktop\steamkeybot\node_modules\trademanager1\lib\classes\TradeOffer.js:405:4)
    at Request._callback (C:\Users\Logan\Desktop\steamkeybot\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\Logan\Desktop\steamkeybot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Logan\Desktop\steamkeybot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Logan\Desktop\steamkeybot\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)

I'm on the latest version and I have tried different versions but it still doesn't work.

**Comment by andrewda** [comment]
What's your code? Are you supplying a callback?

**Comment by braunly** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#sendcallback
