### ISSUE TITLE
Multiple issues.

### ISSUE THREAD

**Issue by Dyceman** [DoctorMcKay/node-steam-tradeoffer-manager#259]
`Offer #2940784598 sent, but requires confirmation
Error: Could not act on confirmation
    at /var/www/tradebot/node_modules/steamcommunity/components/confirmations.js:145:12
    at SteamCommunity.<anonymous> (/var/www/tradebot/node_modules/steamcommunity/components/confirmations.js:276:3)
    at Request._callback (/var/www/tradebot/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/var/www/tradebot/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/var/www/tradebot/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/var/www/tradebot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

`{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at TLSSocket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' }`

**Comment by phiresky** [comment]
I think this is the same issue I also have sometimes. It can be worked around by putting the confirmation code in a retry loop

**Comment by aleko333** [comment]
my bot is very slowly can help me? 5minute=20 Trade

**Comment by Gamesys3** [comment]
Bump Doesn't fire at all now
