### ISSUE TITLE
Offer .send() returns err object with no keys on password reset restriction.

### ISSUE THREAD

**Issue by killemth** [DoctorMcKay/node-steam-tradeoffer-manager#263]
The [send method](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#sendcallback) of the **offer class** returns with an **err object** present in the callback but absent of any keys.

Confirmed that a trade limitation due to a **password reset restriction** is currently active for the account, by visiting a Steam economy item page.

**Comment by DoctorMcKay** [comment]
Could you show what you get if you `console.log` the error?

**Comment by killemth** [comment]
`console.log` of the `err` parameter returns the following...

`Error: There was an error sending your trade offer.  Please try again later.<br><br>You recently forgot and then reset your Steam account's password. In order to protect the items in your inventory, you will be unable to trade for 5 more days.
    at Object.exports.makeAnError (D:\OneDrive\Projects\Razer\Development Trade Bot\node_modules\steam-tradeoffer-manager\lib\helpers.js:17:12)
    at SteamCommunity.manager._community.httpRequestPost (D:\OneDrive\Projects\Razer\Development Trade Bot\node_modules\steam-tradeoffer-manager\lib\classes\TradeOffer.js:349:12)
    at Request._callback (D:\OneDrive\Projects\Razer\Development Trade Bot\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (D:\OneDrive\Projects\Razer\Development Trade Bot\node_modules\steamcommunity\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\OneDrive\Projects\Razer\Development Trade Bot\node_modules\steamcommunity\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\OneDrive\Projects\Razer\Development Trade Bot\node_modules\steamcommunity\node_modules\request\request.js:1085:12)`

Logging a `JSON.stringify()` version returns {}.

**Comment by DoctorMcKay** [comment]
Not a bug. You can't `JSON.stringify` an `Error`.
