### ISSUE TITLE
setCookies with proxy - Error: tunneling socket could not be established

### ISSUE THREAD

**Issue by creazy231** [DoctorMcKay/node-steam-tradeoffer-manager#278]
Hello everyone.

I try to set up the trade offer manager using a proxy. The reason for that is, that steam bans my bots weekly and I think the reason is, that Im runny to many bots on the same IP.

However, that's my code:
![download](https://user-images.githubusercontent.com/13473174/39248806-5beb0598-489d-11e8-8dcd-2b9ecc5c76e0.png)

Console log:
```
Fatal error since we couldn't get our API key
{ Error: tunneling socket could not be established, statusCode=400
    at ClientRequest.onConnect (C:\xampp\htdocs\vuejs\pubgyolo\node_modules\tunnel-agent\index.js:166:19)
    at ClientRequest.g (events.js:291:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:395:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20) code: 'ECONNRESET' }
```

Could anyone explain me whats going wrong? Thanks for help <3

**Comment by Aareksio** [comment]
L668 doesn't work like you'd expect it to. Read `steam-user` docs 😉 

Looks like something wrong with your proxy.
https://httpstatuses.com/400

> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**
