### ISSUE TITLE
Issue with property "appid" of undefined.

### ISSUE THREAD

**Issue by Jorsch21** [DoctorMcKay/node-steam-tradeoffer-manager#279]
Hey,

I´ve really been struggeling with an issue lately. I found this bot/script two days ago and since then, tried to get it to run. It has worked for like 5 minutes, but then failed again. Sadly, I can't even get to that point anymore.

So here's the issue:
C:\Users\Administrator\Desktop\node-steam-trade-farm-master>node bot
Bot Client Logged In!
Main Client Logged In!
The item in which we are using is a/an september 2017 workshop crate #4
Trade offered. Counter is at : 0
Trade #1
Second Account found an Offer!
Second Account, has accepted trade. Now sending it back.
C:\Users\Administrator\Desktop\node-steam-trade-farm-master\node_modules\steam-t
radeoffer-manager\lib\classes\TradeOffer.js:254
if (typeof details.appid === 'undefined' || typeof details.contextid ===
'undefined' || (typeof details.assetid === 'undefined' && typeof details.id ===
'undefined')) {
^

TypeError: Cannot read property 'appid' of undefined
at addItem (C:\Users\Administrator\Desktop\node-steam-trade-farm-master\node
_modules\steam-tradeoffer-manager\lib\classes\TradeOffer.js:254:21)
at TradeOffer.addMyItem (C:\Users\Administrator\Desktop\node-steam-trade-far
m-master\node_modules\steam-tradeoffer-manager\lib\classes\TradeOffer.js:167:9)
at botManager.getInventoryContents (C:\Users\Administrator\Desktop\node-stea
m-trade-farm-master\bot.js:180:25)
at SteamCommunity.<anonymous> (C:\Users\Administrator\Desktop\node-steam-tra
de-farm-master\node_modules\steam-tradeoffer-manager\node_modules\steamcommunity
\components\users.js:415:5)
at Request._callback (C:\Users\Administrator\Desktop\node-steam-trade-farm-m
aster\node_modules\steam-tradeoffer-manager\node_modules\steamcommunity\componen
ts\http.js:67:15)
at Request.self.callback (C:\Users\Administrator\Desktop\node-steam-trade-fa
rm-master\node_modules\request\request.js:186:22)
at emitTwo (events.js:126:13)
at Request.emit (events.js:214:7)
at Request.<anonymous> (C:\Users\Administrator\Desktop\node-steam-trade-farm
-master\node_modules\request\request.js:1163:10)
at emitOne (events.js:116:13)

C:\Users\Administrator\Desktop\node-steam-trade-farm-master>

It somehow fails. I already asked an expert and he told me that the only thing he suspected was that my inventory was empty, which is not the case. He then advised me to contact the github directly. Does anybody know how to fix this error? I´d be really, really grateful, considering I´ve spent so much time trying to figute it out.

If possible, please make the solution somewhat newbie-friendly to understand. Thanks!!

**Comment by DoctorMcKay** [comment]
Please post your issue and code on [the forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/) and you'll get an answer.
