### ISSUE TITLE
Error: LogonSessionReplaced

### ISSUE THREAD

**Issue by chichur** [DoctorMcKay/node-steam-tradeoffer-manager#292]
When i try launch this  [script](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/examples/offloader.js) again.
```
Error: LogonSessionReplaced
    at SteamUser._handleLogOff (C:\var\www\html\nodejs\node_modules\steam-user\c
omponents\logon.js:400:11)
    at SteamUser._handlers.(anonymous function) (C:\var\www\html\nodejs\node_mod
ules\steam-user\components\logon.js:380:7)
    at SteamUser._handleMessage (C:\var\www\html\nodejs\node_modules\steam-user\
components\messages.js:249:30)
    at emitThree (events.js:136:13)
    at CMClient.emit (events.js:217:7)
    at CMClient._netMsgReceived (C:\var\www\html\nodejs\node_modules\steam-clien
t\lib\cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (C:\var\www\html\nodejs\node_modul
es\steam-client\lib\cm_client.js:603:8)
    at CMClient._netMsgReceived (C:\var\www\html\nodejs\node_modules\steam-clien
t\lib\cm_client.js:305:24)
    at emitOne (events.js:116:13)
    at TCPConnection.emit (events.js:211:7)
```

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

This has nothing to do with steam-tradeoffer-manager, that's coming from steam-user.

And the reason is because you need to set `logonID` to something unique in [logOn](https://github.com/DoctorMcKay/node-steam-user#logondetails) if you're logging into the same account from the same public IP.
