### ISSUE TITLE
TypeError thrown due to apparently missing callback

### ISSUE THREAD

**Issue by Lagg** [DoctorMcKay/node-steam-tradeoffer-manager#34]
Hi, I've been using this nifty module for a bit and noticed that it sometimes throws this:

```
/home/anthony/botte/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/index.js:323
                callback(error);
                ^

TypeError: callback is not a function
    at SteamCommunity._checkHttpError (/home/anthony/botte/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/index.js:323:3)
    at Request._callback (/home/anthony/botte/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/components/users.js:260:12)
    at Request.self.callback (/home/anthony/botte/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/anthony/botte/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/anthony/botte/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

```

I'm guessing this occurs when the cookies expire and steam returns 401 or whatever it decides to in that particular moment, and since the manager doesn't do community.login there's no callback ever passed. Am I just being dumb and missing the obvious place I should be setting the callback myself or?

**Comment by DoctorMcKay** [comment]
Looks like you're missing a callback when you're trying to load an inventory. My suspicion is that you're calling `manager.loadInventory(appid, contextid, callback)` instead of `manager.loadInventory(appid, contextid, tradableOnly, callback)`.

**Comment by Lagg** [comment]
This is possible. Things aligned properly and your lib was more or less API compatible with what I had before and this might not actually be working in my favor. Thanks for the tip, will  check and revise. If it turns out to indeed be me being dumb I will close the issue.

**Comment by Lagg** [comment]
Yep it appears that was it. It was the single one that I missed. I'm surprised it even managed to retrieve the inventory at any point at all because of how incompatible the calling conventions between the two are. Thanks again.
